### ISSUE TITLE
"Error: The specified marker is not valid" after upgrade to 0.7.0

### ISSUE THREAD

**Issue by anatolijd** [fog/fog-aws#148]
Have got problem after upgrading to 0.7.0:

When executing this code:
```
zone = dns.zones.find_all{|zone| zone.domain == "#{domain}." }[0]
```
i'm getting the exception:
```
Fog::DNS::AWS::Error: InvalidInput => The specified marker is not valid.
```

**Comment by dblessing** [comment]
:+1: Here, too.

**Comment by anatolijd** [comment]
fixed, thanks.

**Comment by dblessing** [comment]
@anatolijd Fixed in 0.7.1 or 0.7.2? I didn't see any reference to a fix in the commit log. Thanks

**Comment by geemus** [comment]
Sorry to hear you were having this problem, sounds fixed though.

**Comment by FestivalBobcats** [comment]
This was fixed? I'm still seeing the issue in 0.7.3.

**Comment by geemus** [comment]
@FestivalBobcats I didn't personally confirm, but others seemed to indicate it wasn't still a problem for them. Could you provide some more specifics? (maybe just file a new issue for clarity and we can go from there). Thanks!

**Comment by FestivalBobcats** [comment]
I can file a new issue if need be -- but I've circumvented by using 0.6.0. Simply calling ```dns.zones``` raised this error for me. I had simply bumped fog from 1.30.0 -> 1.32.0.

**Comment by marc-** [comment]
Having this issue when running vagrant:
```
/var/lib/gems/2.1.0/gems/excon-0.45.4/lib/excon/middlewares/expects.rb:6:in `response_call': InvalidInput => The specified marker is not valid. (Fog::DNS::AWS::Error)
        from /var/lib/gems/2.1.0/gems/excon-0.45.4/lib/excon/middlewares/response_parser.rb:8:in `response_call'
        from /var/lib/gems/2.1.0/gems/excon-0.45.4/lib/excon/connection.rb:372:in `response'
        from /var/lib/gems/2.1.0/gems/excon-0.45.4/lib/excon/connection.rb:236:in `request'
        from /var/lib/gems/2.1.0/gems/fog-xml-0.1.2/lib/fog/xml/sax_parser_connection.rb:35:in `request'
        from /var/lib/gems/2.1.0/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:7:in `request'
        from /var/lib/gems/2.1.0/gems/fog-aws-0.7.3/lib/fog/aws/dns.rb:141:in `_request'
        from /var/lib/gems/2.1.0/gems/fog-aws-0.7.3/lib/fog/aws/dns.rb:136:in `request'
        from /var/lib/gems/2.1.0/gems/fog-aws-0.7.3/lib/fog/aws/requests/dns/list_hosted_zones.rb:39:in `list_hosted_zones'
        from /var/lib/gems/2.1.0/gems/fog-aws-0.7.3/lib/fog/aws/models/dns/zones.rb:15:in `all'
        from /home/user/.vagrant.d/gems/gems/fog-core-1.32.0/lib/fog/core/collection.rb:113:in `lazy_load'
        from /home/user/.vagrant.d/gems/gems/fog-core-1.32.0/lib/fog/core/collection.rb:17:in `each'
        from /home/user/.vagrant.d/gems/gems/vagrant-aws-extras-0.1.0/lib/vagrant-aws-extras/action/dns.rb:46:in `detect'
        from /home/user/.vagrant.d/gems/gems/vagrant-aws-extras-0.1.0/lib/vagrant-aws-extras/action/dns.rb:46:in `call'
```

**Comment by solud** [comment]
I belive this commit fixes this: https://github.com/fog/fog-aws/commit/2a3750718cef513474987c54b519aa5da9a7b061

**Comment by marc-** [comment]
@solud , I can confirm, your patch fixed it for me. Looking forward for new version.

**Comment by lanej** [comment]
@marc- @solud I just cut 0.7.4 switch should have the patch you require.

**Comment by geemus** [comment]
Thanks!
